GET http://localhost:1307/api/products HTTP/1.1

###

POST http://localhost:1307/api/products HTTP/1.1
Content-Type: application/json
Accept: application/json

{
   "name": "Kaos"
}

###
# create validation error
POST http://localhost:1307/api/products HTTP/1.1
Content-Type: application/json
Accept: application/json

{
   "name": ""
}

###

GET http://localhost:1307/api/products/1 HTTP/1.1

###

PUT http://localhost:1307/api/products/1 HTTP/1.1
Content-Type: application/json
Accept: application/json

{
   "name": "Portable Computer"
}

###

# update validation error
PUT http://localhost:1307/api/products/1 HTTP/1.1
Content-Type: application/json
Accept: application/json

{
   "name": ""
}

###

DELETE http://localhost:1307/api/products/2 HTTP/1.1